# Multi-sensor Semantic Segmentation Configuration
# python train.py --config config/alphaearth_config.yaml
# python scene_classification.py --sensor_name alphaearth --model_name HRNet 
# Model and dataset
model_name: "mHC_cluster" # SwinUNet, BasicUNet, HRNet , MambaHSISeg, mHC_cluster, ssrn
sensor_name: "alphaearth" # landsat8 OR alphaearth OR sentinel2
label_type: "filtered" # "unfiltered" OR "filtered"

# Paths
data_root: "./train_val_test_patches_128x128/patches"
dataset_config: "./train_val_test_patches_128x128/multisensor_dataset_config.json"
output_dir: "./experiments"

# Training hyperparameters
epochs: 100
batch_size: 4
learning_rate: 0.0001
weight_decay: 0.00001

# Loss and optimizer
loss_fn: "cross_entropy"
optimizer: "adamw"
scheduler: "cosine"

# Model settings
ignore_index: -99
class_weights: null

# Training settings
use_amp: true
num_workers: 4
save_every: 10

# Weights & Biases
use_wandb: true
wandb_project: "AlphaEarth_Alberta_2020"
wandb_entity: "saeid_taleghani"

# Random seed
seed: 42