# Multi-sensor Semantic Segmentation Configuration
# python train.py --config config/landsat_config.yaml
# python scene_classification.py --sensor_name landsat8 --model_name HRNet

# Model and dataset
model_name: "SwinUNet" #  SwinUNet, BasicUNet, HRNet
sensor_name: "landsat8" # sentinel2 OR alphaearth
label_type: "filtered"  # or "unfiltered"

# Paths - Use absolute paths or set them relative to project root
data_root: "./train_val_test_patches/patches"
dataset_config: "./train_val_test_patches/multisensor_dataset_config.json"
output_dir: "./experiments"

# Training hyperparameters
epochs: 100
batch_size: 16
learning_rate: 0.0001
weight_decay: 0.00001

# Loss and optimizer
loss_fn: "cross_entropy"
optimizer: "adamw"
scheduler: "cosine"

# Model settings
ignore_index: -99
class_weights: null  # Optional: path to JSON file or list [1.0, 2.0, ...]

# Training settings
use_amp: true
num_workers: 4
save_every: 10

# Weights & Biases
use_wandb: true
wandb_project: "AlphaEarth_Alberta_2020"
wandb_entity: "saeid_taleghani"

# Random seed
seed: 42